openapi: 3.0.0
info:
  title: "Enviar PTV"
  description: "Envía un video de tipo Picture-to-Video (PTV)."
  version: 1.0.0

servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain

paths:
  "/api/send/{instance}":
    post:
      summary: "Enviar PTV"
      description: "Envía un video tipo Picture-to-Video (PTV)."
      parameters:
        - name: instance
          in: path
          required: true
          description: Número de dispositivo
          schema:
            type: string
            example: "51987654321"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - payload
              properties:
                type:
                  type: string
                  example: "sendPtv"
                payload:
                  type: object
                  required:
                    - number
                    - video
                  properties:
                    number:
                      type: string
                      example: "51987654321"
                    video:
                      type: string
                      example: "https://example.com/ptv.mp4"
            example:
              type: sendPtv
              payload:
                number: "51987654321"
                video: "https://example.com/ptv.mp4"
      responses:
        '200':
          description: "PTV enviado exitosamente"
          content:
            application/json:
              schema:
                type: object
                example:
                  key:
                    remoteJid: "51987654321@s.whatsapp.net"
                    fromMe: true
                    id: "3EB0123456789ABCDEF"
                  status: "PENDING"