openapi: 3.0.0
info:
  title: "Enviar audio"
  description: "Envía un archivo de audio o una nota de voz de WhatsApp."
  version: 1.0.0

servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain

paths:
  "/api/send/{instance}":
    post:
      summary: "Enviar audio"
      description: "Envía un archivo de audio o una nota de voz usando el servicio de Evolution."
      parameters:
        - name: instance
          in: path
          required: true
          description: Número de dispositivo
          schema:
            type: string
            example: "51987654321"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - payload
              properties:
                type:
                  type: string
                  example: "sendWhatsAppAudio"
                payload:
                  type: object
                  required:
                    - number
                    - audio
                  properties:
                    number:
                      type: string
                      example: "51987654321"
                    audio:
                      type: string
                      example: "https://example.com/audio.mp3"
            example:
              type: sendWhatsAppAudio
              payload:
                number: "51987654321"
                audio: "https://example.com/audio.mp3"
      responses:
        '200':
          description: "Mensaje de audio enviado exitosamente"
          content:
            application/json:
              schema:
                type: object
                example:
                  key:
                    remoteJid: "51987654321@s.whatsapp.net"
                    fromMe: true
                    id: "3EB0123456789ABCDEF"
                  status: "PENDING"