openapi: 3.0.0
info:
  title: "Enviar botones"
  description: "Envía un mensaje con botones interactivos."
  version: 1.0.0

servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain

paths:
  "/api/send/{instance}":
    post:
      summary: "Enviar botones"
      description: "Envía un mensaje con botones interactivos para que el usuario pueda responder."
      parameters:
        - name: instance
          in: path
          required: true
          description: Número de dispositivo
          schema:
            type: string
            example: "51987654321"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - payload
              properties:
                type:
                  type: string
                  example: "sendButtons"
                payload:
                  type: object
                  required:
                    - number
                    - title
                    - buttons
                  properties:
                    number:
                      type: string
                      example: "51987654321"
                    title:
                      type: string
                      example: "Title Button"
                    description:
                      type: string
                      example: "Description Button"
                    footer:
                      type: string
                      example: "Footer Button"
                    buttons:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            example: "reply"
                          displayText:
                            type: string
                            example: "Respuesta"
                          id:
                            type: string
                            example: "123"
            example:
              type: sendButtons
              payload:
                number: "51987654321"
                title: "Title Button"
                description: "Description Button"
                footer: "Footer Button"
                buttons:
                  - type: "reply"
                    displayText: "Respuesta"
                    id: "123"
      responses:
        '200':
          description: "Mensaje de botones enviado exitosamente"
          content:
            application/json:
              schema:
                type: object
                example:
                  key:
                    remoteJid: "51987654321@s.whatsapp.net"
                    fromMe: true
                    id: "3EB0123456789ABCDEF"
                  status: "PENDING"