openapi: 3.0.0
info:
  title: "QRAPI - Reseller"
  version: 1.0.0
servers:
  - url: https://qr.buho.la
    description: Main Server
  - url: https://{tenant_id}.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
paths:
  "/auth/login":
    post:
      summary: "Login"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "email": "admin@qr.buho.la",
                  "password": "bh0yJj2C"
                }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9...",
                    "user": {
                      "id": 1,
                      "email": "admin@qr.buho.la",
                      "name": "Admin"
                    }
                  }
  "/api/auth/verify_token":
    post:
      summary: "Verify token"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9..."
                }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "valid": true,
                    "message": "Token válido"
                  }
  "/api/auth/register":
    post:
      summary: "Register"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "email": "demo9@gmail.com",
                  "name": "demo9",
                  "password": "12345678",
                  "password_confirmation": "12345678"
                }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Usuario registrado exitosamente",
                    "user": {
                      "id": 1,
                      "email": "demo9@gmail.com",
                      "name": "demo9"
                    }
                  }
  "/api/auth/logout":
    get:
      summary: "User"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Sesión cerrada exitosamente"
                  }