openapi: 3.0.0
info:
  title: "QRAPI - Tenants"
  version: 1.0.0
servers:
  - url: https://qr.buho.la
    description: Main Server
  - url: https://{tenant_id}.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
paths:
  "/api/tenant/list":
    get:
      summary: "List by Filter"
      parameters:
        - name: id
          in: query
          schema:
            type: string
          description: Tenant ID
        - name: domain
          in: query
          schema:
            type: string
          description: Tenant domain
        - name: active
          in: query
          schema:
            type: boolean
          description: Filter by active status
        - name: paginate
          in: query
          schema:
            type: integer
          description: Number of items per page
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "id": "31845898-ba4b-4b59-b932-a6d34730cc55",
                        "name": "EmpresaDemo",
                        "domain": "demooooo",
                        "email": "admin@empresa.com",
                        "active": true
                      }
                    ],
                    "meta": {
                      "current_page": 1,
                      "per_page": 10,
                      "total": 1
                    }
                  }
  "/api/tenant/register":
    post:
      summary: "Register Tenant"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "name": "EmpresaDemo",
                  "domain": "demooooo",
                  "email": "admin@empresa.com",
                  "password": "123456",
                  "plan_id": 1
                }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Tenant registrado exitosamente",
                    "data": {
                      "id": "31845898-ba4b-4b59-b932-a6d34730cc55",
                      "name": "EmpresaDemo",
                      "domain": "demooooo",
                      "email": "admin@empresa.com"
                    }
                  }
  "/api/tenant/delete/{id}":
    delete:
      summary: "Delete Tenant"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Tenant eliminado exitosamente"
                  }